### ISSUE TITLE
dvbapi problem with multi decrypt

### ISSUE THREAD

**Issue by duongpro2004** [Chris230291/NCam-Docker-Test#3]
I use thealhu´s TVHeadend with Ncam docker to watch sly, but when i open 5 channel same time, last channel cant decrypt, but when i close one channel, this channel work again
![image](https://user-images.githubusercontent.com/64676628/225704950-97d64bd0-5a63-4e75-b7c6-6df35de3f1c3.png)

**Comment by Chris230291** [comment]
I think you are best to ask [here](https://github.com/fairbird/NCam) for advice. This is just a Docker image of their work.
